### PR TITLE
Stateful transaction

### LINKED ISSUE #45: Trigger with a default form will error: "Please fill-in the form"
### Describe the problem you discovered

Currently we need to modify any field in the transaction for it to work

### Describe the solution you'd like

We should be able to trigger without having to modify the transaction form

### Epic

_No response_

### LINKED ISSUE #49: How to mock I/O functions?
I/O functions such as `Chain.get_genesis_address/1` currently won't work in the playground due to the fact that is it not connected to the blockchain. 

We have to decide how to handle this, mock? connect to blockchain? .. ?

### PR DESCRIPTION
**Pull request by cluster**
The goal of this PR is to provide a way to get a stateful transaction when using the smart contract trigger function.

Closes #49 
Closes #45

### CODE REVIEW

**Comment by samuelmanzanera** [comment]
Can we have something to initialize the state of the transaction in the trigger testing ?
For example defines the contract in a specific state to test actions using this state at first place.

**Comment by bchamagne** [comment]
I think there's a mixup between trigger transaction and previous contract.
Here's a contract to try:

```elixir
@version 1
condition transaction: [ ]
actions triggered_by: transaction do 
  Contract.set_content "CONTRACT:#{contract.content} TRANSACTION:#{transaction.content}"
end
```

**Comment by bchamagne** [comment]
Screenshot 2023-07-07 at 09-44-46 Home - Archethic Playground

Looks like contract.content was not set to 0 as I expected

**Comment by samuelmanzanera** [comment]
> Screenshot 2023-07-07 at 09-44-46 Home - Archethic Playground
> 
> Looks like contract.content was not set to 0 as I expected

This is because the form is about the new transaction, not the previous one.
Reason of my previous content above.

**Pull request merged**
